# Generated by Django 6.0.1 on 2026-01-12 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CropSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nitrogen', models.FloatField(help_text='Nitrogen content (N)')),
                ('phosphorus', models.FloatField(help_text='Phosphorus content (P)')),
                ('potassium', models.FloatField(help_text='Potassium content (K)')),
                ('temperature', models.FloatField(help_text='Temperature in Celsius')),
                ('humidity', models.FloatField(help_text='Humidity percentage')),
                ('ph', models.FloatField(help_text='Soil pH level')),
                ('rainfall', models.FloatField(help_text='Rainfall in mm')),
                ('recommended_crop', models.CharField(help_text='Recommended crop name', max_length=255)),
                ('recommendation_message', models.TextField(help_text='Full recommendation message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rating', models.FloatField(blank=True, help_text='User rating of recommendation (1-5)', null=True)),
                ('session_id', models.BigIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Crop Suggestion',
                'verbose_name_plural': 'Crop Suggestions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FertAIResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nitrogen', models.FloatField()),
                ('phosphorus', models.FloatField()),
                ('potassium', models.FloatField()),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('moisture', models.FloatField()),
                ('crop_type', models.CharField(max_length=255)),
                ('soil_type', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=255)),
                ('asked_at', models.DateTimeField(auto_now_add=True)),
                ('answer_rating', models.FloatField(blank=True, null=True)),
                ('session_id', models.BigIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecAIResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nitrogen', models.FloatField()),
                ('phosphorus', models.FloatField()),
                ('potassium', models.FloatField()),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('ph', models.FloatField()),
                ('rainfall', models.FloatField()),
                ('answer', models.CharField(max_length=255)),
                ('asked_at', models.DateTimeField(auto_now_add=True)),
                ('answer_rating', models.FloatField(blank=True, null=True)),
                ('session_id', models.BigIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
