# Generated by Django 6.0.1 on 2026-01-12 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_responses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FertilizerSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nitrogen', models.FloatField(help_text='Nitrogen content')),
                ('phosphorous', models.FloatField(help_text='Phosphorous content')),
                ('potassium', models.FloatField(help_text='Potassium content')),
                ('soil_type', models.CharField(help_text='Type of soil', max_length=100)),
                ('crop_type', models.CharField(help_text='Type of crop', max_length=100)),
                ('temperature', models.FloatField(help_text='Temperature in Celsius')),
                ('humidity', models.FloatField(help_text='Humidity percentage')),
                ('moisture', models.FloatField(help_text='Soil moisture percentage')),
                ('recommended_fertilizer', models.CharField(help_text='Recommended fertilizer name', max_length=255)),
                ('recommendation_message', models.TextField(help_text='Full recommendation message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rating', models.FloatField(blank=True, help_text='User rating of recommendation (1-5)', null=True)),
                ('session_id', models.BigIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fertilizer Suggestion',
                'verbose_name_plural': 'Fertilizer Suggestions',
                'ordering': ['-created_at'],
            },
        ),
    ]
