# Generated by Django 6.0.1 on 2026-01-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_responses', '0002_fertilizersuggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropsuggestion',
            name='session_id',
            field=models.CharField(blank=True, help_text='Session identifier', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fertairesponse',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fertilizersuggestion',
            name='session_id',
            field=models.CharField(blank=True, help_text='Session identifier', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recairesponse',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
