# Generated by Django 6.0.1 on 2026-01-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_responses', '0003_alter_cropsuggestion_session_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropsuggestion',
            name='recommendation_message',
            field=models.TextField(blank=True, help_text='Full recommendation message', null=True),
        ),
        migrations.AlterField(
            model_name='cropsuggestion',
            name='recommended_crop',
            field=models.CharField(blank=True, help_text='Recommended crop name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fertilizersuggestion',
            name='recommendation_message',
            field=models.TextField(blank=True, help_text='Full recommendation message', null=True),
        ),
        migrations.AlterField(
            model_name='fertilizersuggestion',
            name='recommended_fertilizer',
            field=models.CharField(blank=True, help_text='Recommended fertilizer name', max_length=255, null=True),
        ),
    ]
