# Generated by Django 6.0 on 2026-01-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_alter_rentitemorders_rent_taker_alter_rentowner_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentowner',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
