# Generated by Django 6.0 on 2026-01-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_alter_rentowner_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentowner',
            name='contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rentowner',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
