# Generated by Django 6.0 on 2026-01-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
