# Generated by Django 5.1.4 on 2026-01-03 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0002_farmer_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farmer',
            options={'ordering': ['id']},
        ),
    ]
