# Generated by Django 5.1.4 on 2025-01-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_method',
            field=models.CharField(choices=[('Credit Card', 'Credit Card'), ('Bank Transfer', 'Bank Transfer'), ('Bkash', 'Bkash'), ('Nagad', 'Nagad'), ('Cash', 'Cash')], max_length=50),
        ),
    ]
